name: Publish

on:
  release:
    types: [published]

permissions: read-all

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Publish release of assertor
      env:
        CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
      run: cargo publish -p assertor
